name: irida_qr
description: App to read and store QR codes
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  iconsax_plus: ^1.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  lottie: ^3.3.1
  mobile_scanner: ^6.0.7
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/lotties/
